files:
  - source: /en-US/info/*.json
    translation: /%locale%/info/%original_file_name%
  - source: /en-US/**.json
    translation: /%locale%/%original_file_name%
  - source: /en-US/music/**.json
    translation: /%locale%/music/%original_file_name%
  - source: /en-US/anime/**.json
    translation: /%locale%/anime/%original_file_name%
  - source: /en-US/economy/**.json
    translation: /%locale%/economy/%original_file_name%
