files:
  - source: /language-meta.json
    ignore:
      - /README.md
    translation: /%locale%.json
  - source: /en-US/info/*.json
    translation: /%locale%/info/*.json
  - source: /en-US/**.json
    translation: /%locale%/**.json
  - source: /en-US/music/**.json
    translation: /%locale%/music/**.json
