files:
  - source: /language-meta.json
    ignore:
      - /README.md
    translation: /%locale%.json
  - source: /en-US/info/*.json
    translation: /en-US/info/%locale%.json
  - source: /en-US/**.json
    translation: /en-US/%locale%.json
  - source: /en-US/music/**.json
    translation: /en-US/music/%locale%.json
