files:
  - source: /language-meta.json
    ignore:
      - /README.md
    translation: /%locale%.json
  - source: /en-US/info/*.json
    translation: /%locale%/info/%file_name%
  - source: /en-US/**.json
    translation: /%locale%/%file_name%
  - source: /en-US/music/**.json
    translation: /%locale%/music/%file_name%
